2021-07-11 23:34:06.305449 (MainThread): Running with dbt=0.19.2
2021-07-11 23:34:06.373755 (MainThread): running dbt with arguments Namespace(cls=<class 'dbt.task.rpc.server.RPCServerTask'>, debug=False, defer=None, exclude=None, host='0.0.0.0', log_cache_events=False, log_format='default', models=None, partial_parse=True, port=8580, profile='user', profiles_dir='/usr/src/develop/.dbt', project_dir=None, record_timing_info=None, rpc_method=None, single_threaded=False, state=None, strict=False, target=None, test_new_parser=False, threads=None, use_cache=True, use_colors=None, vars='{}', version_check=True, warn_error=False, which='rpc', write_json=True)
2021-07-11 23:34:06.392910 (Thread-1): Parsing macros/adapters.sql
2021-07-11 23:34:06.400988 (MainThread): Tracking: tracking
2021-07-11 23:34:06.414299 (Thread-1): Parsing macros/relations.sql
2021-07-11 23:34:06.419195 (Thread-1): Parsing macros/catalog.sql
2021-07-11 23:34:06.421713 (Thread-1): Parsing macros/materializations/snapshot_merge.sql
2021-07-11 23:34:06.426476 (Thread-1): Parsing macros/core.sql
2021-07-11 23:34:06.430943 (Thread-1): Parsing macros/materializations/helpers.sql
2021-07-11 23:34:06.439975 (Thread-1): Parsing macros/materializations/common/merge.sql
2021-07-11 23:34:06.454128 (Thread-1): Parsing macros/materializations/snapshot/snapshot_merge.sql
2021-07-11 23:34:06.456090 (Thread-1): Parsing macros/materializations/snapshot/strategies.sql
2021-07-11 23:34:06.473801 (Thread-1): Parsing macros/materializations/snapshot/snapshot.sql
2021-07-11 23:34:06.508572 (MainThread): Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6e9ada17f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6e9478a370>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6e9478a340>]}
2021-07-11 23:34:06.508965 (MainThread): Serving RPC server at 0.0.0.0:8580, pid=16
2021-07-11 23:34:06.509199 (MainThread): Supported methods: ['cli_args', 'compile', 'compile_sql', 'deps', 'docs.generate', 'gc', 'get-manifest', 'kill', 'poll', 'ps', 'run', 'run-operation', 'run_sql', 'seed', 'snapshot', 'snapshot-freshness', 'status', 'test']
2021-07-11 23:34:06.509432 (Thread-1): Parsing macros/materializations/view/create_or_replace_view.sql
2021-07-11 23:34:06.509570 (MainThread): Send requests to http://localhost:8580/jsonrpc
2021-07-11 23:34:06.514822 (Thread-1): Parsing macros/materializations/view/view.sql
2021-07-11 23:34:06.521130 (Thread-1): Parsing macros/materializations/seed/seed.sql
2021-07-11 23:34:06.541604 (Thread-1): Parsing macros/materializations/table/table.sql
2021-07-11 23:34:06.548132 (Thread-1): Parsing macros/materializations/incremental/helpers.sql
2021-07-11 23:34:06.549932 (Thread-1): Parsing macros/materializations/incremental/incremental.sql
2021-07-11 23:34:06.555873 (Thread-1): Parsing macros/etc/is_incremental.sql
2021-07-11 23:34:06.557453 (Thread-1): Parsing macros/etc/query.sql
2021-07-11 23:34:06.558520 (Thread-1): Parsing macros/etc/datetime.sql
2021-07-11 23:34:06.567642 (Thread-1): Parsing macros/etc/get_custom_alias.sql
2021-07-11 23:34:06.568583 (Thread-1): Parsing macros/etc/get_custom_database.sql
2021-07-11 23:34:06.570275 (Thread-1): Parsing macros/etc/get_custom_schema.sql
2021-07-11 23:34:06.572237 (Thread-1): Parsing macros/schema_tests/not_null.sql
2021-07-11 23:34:06.573743 (Thread-1): Parsing macros/schema_tests/accepted_values.sql
2021-07-11 23:34:06.576401 (Thread-1): Parsing macros/schema_tests/relationships.sql
2021-07-11 23:34:06.578259 (Thread-1): Parsing macros/schema_tests/unique.sql
2021-07-11 23:34:06.579980 (Thread-1): Parsing macros/adapters/common.sql
2021-07-11 23:34:06.785481 (Thread-1): Acquiring new postgres connection "model.my_new_project.using_dbt_utils_macros".
2021-07-11 23:34:06.904542 (Thread-1): Acquiring new postgres connection "model.my_new_project.population".
2021-07-11 23:34:06.910143 (Thread-1): Acquiring new postgres connection "model.my_new_project.using_variable".
2021-07-11 23:34:06.916622 (Thread-1): Acquiring new postgres connection "model.my_new_project.covid19_latest_stats".
2021-07-11 23:34:07.032012 (Thread-1): [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.my_new_project.example

2021-07-11 23:34:07.032460 (Thread-1): Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '30d45c14-a17d-4a29-953f-f681c6554c5f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6e93328d60>]}
2021-07-11 23:34:07.208096 (Thread-2): handling status request
2021-07-11 23:34:07.208381 (Thread-2): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '30d45c14-a17d-4a29-953f-f681c6554c5f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6e933838b0>]}
2021-07-11 23:34:07.209233 (Thread-2): sending response (<Response 9418 bytes [200 OK]>) to 10.0.4.229
2021-07-11 23:34:07.225123 (Thread-3): handling status request
2021-07-11 23:34:07.225320 (Thread-3): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '30d45c14-a17d-4a29-953f-f681c6554c5f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6e933b07f0>]}
2021-07-11 23:34:07.225975 (Thread-3): sending response (<Response 9418 bytes [200 OK]>) to 10.0.11.120
2021-07-11 23:34:07.247417 (Thread-4): handling status request
2021-07-11 23:34:07.247631 (Thread-4): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '30d45c14-a17d-4a29-953f-f681c6554c5f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6e9350c8e0>]}
2021-07-11 23:34:07.248248 (Thread-4): sending response (<Response 9418 bytes [200 OK]>) to 10.0.31.252
2021-07-11 23:34:07.255016 (Thread-5): handling status request
2021-07-11 23:34:07.255251 (Thread-5): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '30d45c14-a17d-4a29-953f-f681c6554c5f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6e93383c70>]}
2021-07-11 23:34:07.255863 (Thread-5): sending response (<Response 9418 bytes [200 OK]>) to 10.0.23.95
2021-07-11 23:34:07.269144 (Thread-6): handling ps request
2021-07-11 23:34:07.269320 (Thread-6): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '30d45c14-a17d-4a29-953f-f681c6554c5f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6e932ea100>]}
2021-07-11 23:34:07.269694 (Thread-6): sending response (<Response 105 bytes [200 OK]>) to 10.0.32.40
2021-07-11 23:36:49.243060 (MainThread): Running with dbt=0.19.2
2021-07-11 23:36:49.313485 (MainThread): running dbt with arguments Namespace(cls=<class 'dbt.task.rpc.server.RPCServerTask'>, debug=False, defer=None, exclude=None, host='0.0.0.0', log_cache_events=False, log_format='default', models=None, partial_parse=True, port=8580, profile='user', profiles_dir='/usr/src/develop/.dbt', project_dir=None, record_timing_info=None, rpc_method=None, single_threaded=False, state=None, strict=False, target=None, test_new_parser=False, threads=None, use_cache=True, use_colors=None, vars='{}', version_check=True, warn_error=False, which='rpc', write_json=True)
2021-07-11 23:36:49.320297 (MainThread): Tracking: tracking
2021-07-11 23:36:49.334046 (Thread-1): Parsing macros/adapters.sql
2021-07-11 23:36:49.355225 (Thread-1): Parsing macros/relations.sql
2021-07-11 23:36:49.356848 (Thread-1): Parsing macros/catalog.sql
2021-07-11 23:36:49.359356 (Thread-1): Parsing macros/materializations/snapshot_merge.sql
2021-07-11 23:36:49.363019 (MainThread): Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9fc8ebeeb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9fc2855a60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9fc285af40>]}
2021-07-11 23:36:49.363433 (MainThread): Serving RPC server at 0.0.0.0:8580, pid=16
2021-07-11 23:36:49.363728 (Thread-1): Parsing macros/core.sql
2021-07-11 23:36:49.363895 (MainThread): Supported methods: ['cli_args', 'compile', 'compile_sql', 'deps', 'docs.generate', 'gc', 'get-manifest', 'kill', 'poll', 'ps', 'run', 'run-operation', 'run_sql', 'seed', 'snapshot', 'snapshot-freshness', 'status', 'test']
2021-07-11 23:36:49.367941 (MainThread): Send requests to http://localhost:8580/jsonrpc
2021-07-11 23:36:49.368333 (Thread-1): Parsing macros/materializations/helpers.sql
2021-07-11 23:36:49.377283 (Thread-1): Parsing macros/materializations/common/merge.sql
2021-07-11 23:36:49.391354 (Thread-1): Parsing macros/materializations/snapshot/snapshot_merge.sql
2021-07-11 23:36:49.393088 (Thread-1): Parsing macros/materializations/snapshot/strategies.sql
2021-07-11 23:36:49.410337 (Thread-1): Parsing macros/materializations/snapshot/snapshot.sql
2021-07-11 23:36:49.440854 (Thread-1): Parsing macros/materializations/view/create_or_replace_view.sql
2021-07-11 23:36:49.445744 (Thread-1): Parsing macros/materializations/view/view.sql
2021-07-11 23:36:49.451815 (Thread-1): Parsing macros/materializations/seed/seed.sql
2021-07-11 23:36:49.471995 (Thread-1): Parsing macros/materializations/table/table.sql
2021-07-11 23:36:49.478483 (Thread-1): Parsing macros/materializations/incremental/helpers.sql
2021-07-11 23:36:49.480282 (Thread-1): Parsing macros/materializations/incremental/incremental.sql
2021-07-11 23:36:49.486153 (Thread-1): Parsing macros/etc/is_incremental.sql
2021-07-11 23:36:49.487757 (Thread-1): Parsing macros/etc/query.sql
2021-07-11 23:36:49.488812 (Thread-1): Parsing macros/etc/datetime.sql
2021-07-11 23:36:49.497885 (Thread-1): Parsing macros/etc/get_custom_alias.sql
2021-07-11 23:36:49.498851 (Thread-1): Parsing macros/etc/get_custom_database.sql
2021-07-11 23:36:49.500491 (Thread-1): Parsing macros/etc/get_custom_schema.sql
2021-07-11 23:36:49.502474 (Thread-1): Parsing macros/schema_tests/not_null.sql
2021-07-11 23:36:49.503998 (Thread-1): Parsing macros/schema_tests/accepted_values.sql
2021-07-11 23:36:49.506676 (Thread-1): Parsing macros/schema_tests/relationships.sql
2021-07-11 23:36:49.508537 (Thread-1): Parsing macros/schema_tests/unique.sql
2021-07-11 23:36:49.510272 (Thread-1): Parsing macros/adapters/common.sql
2021-07-11 23:36:49.716485 (Thread-1): Acquiring new postgres connection "model.my_new_project.using_dbt_utils_macros".
2021-07-11 23:36:49.838115 (Thread-1): Acquiring new postgres connection "model.my_new_project.population".
2021-07-11 23:36:49.843836 (Thread-1): Acquiring new postgres connection "model.my_new_project.using_variable".
2021-07-11 23:36:49.850210 (Thread-1): Acquiring new postgres connection "model.my_new_project.covid19_latest_stats".
2021-07-11 23:36:49.950471 (Thread-1): [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.my_new_project.example

2021-07-11 23:36:49.950926 (Thread-1): Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '3b89af83-316b-4b8a-9261-5739925493ab', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9fc1404d60>]}
2021-07-11 23:36:50.806759 (Thread-2): handling status request
2021-07-11 23:36:50.807084 (Thread-2): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '3b89af83-316b-4b8a-9261-5739925493ab', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9fc28be190>]}
2021-07-11 23:36:50.807911 (Thread-2): sending response (<Response 9544 bytes [200 OK]>) to 10.0.15.143
2021-07-11 23:36:50.851414 (Thread-3): handling status request
2021-07-11 23:36:50.851657 (Thread-3): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '3b89af83-316b-4b8a-9261-5739925493ab', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9fc282a250>]}
2021-07-11 23:36:50.852367 (Thread-3): sending response (<Response 9544 bytes [200 OK]>) to 10.0.16.173
2021-07-11 23:36:50.867968 (Thread-4): handling status request
2021-07-11 23:36:50.868176 (Thread-4): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '3b89af83-316b-4b8a-9261-5739925493ab', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9fc2bfcb20>]}
2021-07-11 23:36:50.868826 (Thread-4): sending response (<Response 9544 bytes [200 OK]>) to 10.0.16.236
2021-07-11 23:36:50.881209 (Thread-5): handling status request
2021-07-11 23:36:50.881418 (Thread-5): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '3b89af83-316b-4b8a-9261-5739925493ab', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9fc15027c0>]}
2021-07-11 23:36:50.882000 (Thread-5): sending response (<Response 9544 bytes [200 OK]>) to 10.0.23.95
2021-07-11 23:36:50.884934 (Thread-6): handling ps request
2021-07-11 23:36:50.885116 (Thread-6): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '3b89af83-316b-4b8a-9261-5739925493ab', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9fc13c6580>]}
2021-07-11 23:36:50.885476 (Thread-6): sending response (<Response 105 bytes [200 OK]>) to 10.0.8.196
2021-07-11 23:46:12.479178 (Thread-7): handling status request
2021-07-11 23:46:12.481291 (Thread-7): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '3b89af83-316b-4b8a-9261-5739925493ab', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9fc13c6280>]}
2021-07-11 23:46:12.482038 (Thread-7): sending response (<Response 9544 bytes [200 OK]>) to 10.0.32.40
2021-07-11 23:46:12.702303 (Thread-8): handling run_sql request
2021-07-11 23:46:12.702603 (Thread-8): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '3b89af83-316b-4b8a-9261-5739925493ab', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9fc13c6f70>]}
2021-07-11 23:46:12.704952 (Thread-8): Connection 'model.my_new_project.covid19_latest_stats' was properly closed.
2021-07-11 23:46:14.332476 (Thread-8): sending response (<Response 138 bytes [200 OK]>) to 10.0.40.20
2021-07-11 23:46:14.343338 (MainThread): Acquiring new postgres connection "rpc.my_new_project.request".
2021-07-11 23:46:14.361178 (MainThread): Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': '6b58123d-95fb-4ce7-830c-1d7fb7899ac2', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fae59345df0>]}
2021-07-11 23:46:14.361418 (MainThread): Found 4 models, 2 tests, 0 snapshots, 0 analyses, 138 macros, 0 operations, 0 seed files, 0 sources, 0 exposures
2021-07-11 23:46:14.361800 (Thread-1): Acquiring new postgres connection "rpc.my_new_project.request".
2021-07-11 23:46:14.361906 (Thread-1): Compiling rpc.my_new_project.request
2021-07-11 23:46:14.364279 (Thread-1): finished collecting timing info
2021-07-11 23:46:14.364395 (Thread-1): Using postgres connection "rpc.my_new_project.request".
2021-07-11 23:46:14.364447 (Thread-1): On rpc.my_new_project.request: select * 
from "d15em1n30ihttu"."dbt_ealizadeh"."population" 
join "d15em1n30ihttu"."dbt_ealizadeh"."covid19_latest_stats" 
where code='USA'
limit 500
/* limit added automatically by dbt cloud */
2021-07-11 23:46:14.364500 (Thread-1): Opening a new connection, currently in state init
2021-07-11 23:46:14.411172 (Thread-1): Postgres error: syntax error at or near "where"
LINE 4: where code='USA'
        ^

2021-07-11 23:46:14.411311 (Thread-1): finished collecting timing info
2021-07-11 23:46:14.411399 (Thread-1): On rpc.my_new_project.request: Close
2021-07-11 23:46:14.411599 (Thread-1): Got an exception: Database Error
  syntax error at or near "where"
  LINE 4: where code='USA'
          ^
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/postgres/connections.py", line 47, in exception_handler
    yield
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/sql/connections.py", line 80, in add_query
    cursor.execute(sql, bindings)
psycopg2.errors.SyntaxError: syntax error at or near "where"
LINE 4: where code='USA'
        ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 344, in safe_run
    result = self.compile_and_execute(manifest, ctx)
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 287, in compile_and_execute
    result = self.run(ctx.node, manifest)
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 389, in run
    return self.execute(compiled_node, manifest)
  File "/usr/local/lib/python3.8/dist-packages/dbt/rpc/node_runners.py", line 90, in execute
    _, execute_result = self.adapter.execute(
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/base/impl.py", line 227, in execute
    return self.connections.execute(
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/sql/connections.py", line 124, in execute
    _, cursor = self.add_query(sql, auto_begin)
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/sql/connections.py", line 87, in add_query
    return connection, cursor
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/postgres/connections.py", line 58, in exception_handler
    raise dbt.exceptions.DatabaseException(str(e).strip()) from e
dbt.exceptions.DatabaseException: Database Error
  syntax error at or near "where"
  LINE 4: where code='USA'
          ^
2021-07-11 23:46:14.412720 (Thread-1): Got exception RPCException(10003, Database Error, {'type': 'DatabaseException', 'message': 'Database Error in rpc request (from remote system)\n  syntax error at or near "where"\n  LINE 4: where code=\'USA\'\n          ^', 'raw_sql': 'select * \nfrom {{ref(\'population\')}} \njoin {{ref(\'covid19_latest_stats\')}} \nwhere code=\'{{ var("selected_country") }}\'\nlimit 500\n/* limit added automatically by dbt cloud */', 'compiled_sql': 'select * \nfrom "d15em1n30ihttu"."dbt_ealizadeh"."population" \njoin "d15em1n30ihttu"."dbt_ealizadeh"."covid19_latest_stats" \nwhere code=\'USA\'\nlimit 500\n/* limit added automatically by dbt cloud */', 'tags': None}, None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/rpc/sql_commands.py", line 145, in _in_thread
    self.node_results.append(runner.safe_run(self.manifest))
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 360, in safe_run
    result = self.error_result(ctx.node, error, started, [])
  File "/usr/local/lib/python3.8/dist-packages/dbt/rpc/node_runners.py", line 56, in error_result
    raise error
dbt.rpc.error.RPCException: RPCException(10003, Database Error, {'type': 'DatabaseException', 'message': 'Database Error in rpc request (from remote system)\n  syntax error at or near "where"\n  LINE 4: where code=\'USA\'\n          ^', 'raw_sql': 'select * \nfrom {{ref(\'population\')}} \njoin {{ref(\'covid19_latest_stats\')}} \nwhere code=\'{{ var("selected_country") }}\'\nlimit 500\n/* limit added automatically by dbt cloud */', 'compiled_sql': 'select * \nfrom "d15em1n30ihttu"."dbt_ealizadeh"."population" \njoin "d15em1n30ihttu"."dbt_ealizadeh"."covid19_latest_stats" \nwhere code=\'USA\'\nlimit 500\n/* limit added automatically by dbt cloud */', 'tags': None}, None)
2021-07-11 23:46:14.625869 (Thread-9): handling poll request
2021-07-11 23:46:14.626207 (Thread-9): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '3b89af83-316b-4b8a-9261-5739925493ab', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9fc2bfc9a0>]}
2021-07-11 23:46:14.627138 (Thread-9): sending response (<Response 9226 bytes [200 OK]>) to 10.0.42.143
2021-07-11 23:46:23.721729 (Thread-10): handling status request
2021-07-11 23:46:23.722011 (Thread-10): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '3b89af83-316b-4b8a-9261-5739925493ab', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9fc13bff40>]}
2021-07-11 23:46:23.722880 (Thread-10): sending response (<Response 9544 bytes [200 OK]>) to 10.0.4.229
2021-07-11 23:46:23.969413 (Thread-11): handling run_sql request
2021-07-11 23:46:23.969696 (Thread-11): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '3b89af83-316b-4b8a-9261-5739925493ab', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9fc13bf940>]}
2021-07-11 23:46:25.624393 (Thread-11): sending response (<Response 138 bytes [200 OK]>) to 10.0.42.143
2021-07-11 23:46:25.637037 (MainThread): Acquiring new postgres connection "rpc.my_new_project.request".
2021-07-11 23:46:25.648636 (MainThread): Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': '1b0df8e5-e022-415e-9c4e-2bc1b78889f7', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6b92388dc0>]}
2021-07-11 23:46:25.648862 (MainThread): Found 4 models, 2 tests, 0 snapshots, 0 analyses, 138 macros, 0 operations, 0 seed files, 0 sources, 0 exposures
2021-07-11 23:46:25.649226 (Thread-1): Acquiring new postgres connection "rpc.my_new_project.request".
2021-07-11 23:46:25.649331 (Thread-1): Compiling rpc.my_new_project.request
2021-07-11 23:46:25.651611 (Thread-1): finished collecting timing info
2021-07-11 23:46:25.651720 (Thread-1): Using postgres connection "rpc.my_new_project.request".
2021-07-11 23:46:25.651770 (Thread-1): On rpc.my_new_project.request: select * 
from "d15em1n30ihttu"."dbt_ealizadeh"."population" 
join on "d15em1n30ihttu"."dbt_ealizadeh"."covid19_latest_stats" 
where code='USA'
limit 500
/* limit added automatically by dbt cloud */
2021-07-11 23:46:25.651824 (Thread-1): Opening a new connection, currently in state init
2021-07-11 23:46:25.669453 (Thread-1): Postgres error: syntax error at or near "on"
LINE 3: join on "d15em1n30ihttu"."dbt_ealizadeh"."covid19_latest_sta...
             ^

2021-07-11 23:46:25.669578 (Thread-1): finished collecting timing info
2021-07-11 23:46:25.669663 (Thread-1): On rpc.my_new_project.request: Close
2021-07-11 23:46:25.669814 (Thread-1): Got an exception: Database Error
  syntax error at or near "on"
  LINE 3: join on "d15em1n30ihttu"."dbt_ealizadeh"."covid19_latest_sta...
               ^
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/postgres/connections.py", line 47, in exception_handler
    yield
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/sql/connections.py", line 80, in add_query
    cursor.execute(sql, bindings)
psycopg2.errors.SyntaxError: syntax error at or near "on"
LINE 3: join on "d15em1n30ihttu"."dbt_ealizadeh"."covid19_latest_sta...
             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 344, in safe_run
    result = self.compile_and_execute(manifest, ctx)
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 287, in compile_and_execute
    result = self.run(ctx.node, manifest)
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 389, in run
    return self.execute(compiled_node, manifest)
  File "/usr/local/lib/python3.8/dist-packages/dbt/rpc/node_runners.py", line 90, in execute
    _, execute_result = self.adapter.execute(
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/base/impl.py", line 227, in execute
    return self.connections.execute(
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/sql/connections.py", line 124, in execute
    _, cursor = self.add_query(sql, auto_begin)
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/sql/connections.py", line 87, in add_query
    return connection, cursor
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/postgres/connections.py", line 58, in exception_handler
    raise dbt.exceptions.DatabaseException(str(e).strip()) from e
dbt.exceptions.DatabaseException: Database Error
  syntax error at or near "on"
  LINE 3: join on "d15em1n30ihttu"."dbt_ealizadeh"."covid19_latest_sta...
               ^
2021-07-11 23:46:25.670895 (Thread-1): Got exception RPCException(10003, Database Error, {'type': 'DatabaseException', 'message': 'Database Error in rpc request (from remote system)\n  syntax error at or near "on"\n  LINE 3: join on "d15em1n30ihttu"."dbt_ealizadeh"."covid19_latest_sta...\n               ^', 'raw_sql': 'select * \nfrom {{ref(\'population\')}} \njoin on {{ref(\'covid19_latest_stats\')}} \nwhere code=\'{{ var("selected_country") }}\'\nlimit 500\n/* limit added automatically by dbt cloud */', 'compiled_sql': 'select * \nfrom "d15em1n30ihttu"."dbt_ealizadeh"."population" \njoin on "d15em1n30ihttu"."dbt_ealizadeh"."covid19_latest_stats" \nwhere code=\'USA\'\nlimit 500\n/* limit added automatically by dbt cloud */', 'tags': None}, None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/rpc/sql_commands.py", line 145, in _in_thread
    self.node_results.append(runner.safe_run(self.manifest))
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 360, in safe_run
    result = self.error_result(ctx.node, error, started, [])
  File "/usr/local/lib/python3.8/dist-packages/dbt/rpc/node_runners.py", line 56, in error_result
    raise error
dbt.rpc.error.RPCException: RPCException(10003, Database Error, {'type': 'DatabaseException', 'message': 'Database Error in rpc request (from remote system)\n  syntax error at or near "on"\n  LINE 3: join on "d15em1n30ihttu"."dbt_ealizadeh"."covid19_latest_sta...\n               ^', 'raw_sql': 'select * \nfrom {{ref(\'population\')}} \njoin on {{ref(\'covid19_latest_stats\')}} \nwhere code=\'{{ var("selected_country") }}\'\nlimit 500\n/* limit added automatically by dbt cloud */', 'compiled_sql': 'select * \nfrom "d15em1n30ihttu"."dbt_ealizadeh"."population" \njoin on "d15em1n30ihttu"."dbt_ealizadeh"."covid19_latest_stats" \nwhere code=\'USA\'\nlimit 500\n/* limit added automatically by dbt cloud */', 'tags': None}, None)
2021-07-11 23:46:25.828256 (Thread-12): handling poll request
2021-07-11 23:46:25.828559 (Thread-12): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '3b89af83-316b-4b8a-9261-5739925493ab', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9fc13c92e0>]}
2021-07-11 23:46:25.829432 (Thread-12): sending response (<Response 9617 bytes [200 OK]>) to 10.0.16.173
2021-07-11 23:46:25.928822 (Thread-13): Got an acceptable cached parse result
2021-07-11 23:46:26.085091 (Thread-13): Acquiring new postgres connection "model.my_new_project.using_variable".
2021-07-11 23:46:26.176661 (Thread-13): [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.my_new_project.example

2021-07-11 23:46:26.177162 (Thread-13): Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '3b89af83-316b-4b8a-9261-5739925493ab', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9fc0ae5d60>]}
2021-07-11 23:46:26.279370 (Thread-14): handling status request
2021-07-11 23:46:26.279642 (Thread-14): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '3b89af83-316b-4b8a-9261-5739925493ab', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9fc0ae5c10>]}
2021-07-11 23:46:26.280170 (Thread-14): sending response (<Response 1620 bytes [200 OK]>) to 10.0.24.195
2021-07-11 23:46:26.294296 (Thread-15): handling status request
2021-07-11 23:46:26.294524 (Thread-15): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '3b89af83-316b-4b8a-9261-5739925493ab', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9fc0a2cfd0>]}
2021-07-11 23:46:26.294937 (Thread-15): sending response (<Response 1620 bytes [200 OK]>) to 10.0.11.120
2021-07-11 23:46:26.321999 (Thread-16): handling status request
2021-07-11 23:46:26.322222 (Thread-16): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '3b89af83-316b-4b8a-9261-5739925493ab', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9fc0ae5a30>]}
2021-07-11 23:46:26.322647 (Thread-16): sending response (<Response 1620 bytes [200 OK]>) to 10.0.11.120
2021-07-11 23:46:27.560175 (Thread-17): handling status request
2021-07-11 23:46:27.560458 (Thread-17): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '3b89af83-316b-4b8a-9261-5739925493ab', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9fc145fc40>]}
2021-07-11 23:46:27.560955 (Thread-17): sending response (<Response 1620 bytes [200 OK]>) to 10.0.13.135
2021-07-11 23:46:27.785075 (Thread-18): handling run_sql request
2021-07-11 23:46:27.785368 (Thread-18): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '3b89af83-316b-4b8a-9261-5739925493ab', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9fc0ae53a0>]}
2021-07-11 23:46:27.786537 (Thread-18): Connection 'model.my_new_project.using_variable' was properly closed.
2021-07-11 23:46:29.424638 (Thread-18): sending response (<Response 138 bytes [200 OK]>) to 10.0.32.40
2021-07-11 23:46:29.435586 (MainThread): Acquiring new postgres connection "rpc.my_new_project.request".
2021-07-11 23:46:29.447410 (MainThread): Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': 'fb3f8f7c-e247-46fc-bdbc-da2756f14531', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f24dddb8df0>]}
2021-07-11 23:46:29.447637 (MainThread): Found 4 models, 2 tests, 0 snapshots, 0 analyses, 138 macros, 0 operations, 0 seed files, 0 sources, 0 exposures
2021-07-11 23:46:29.448023 (Thread-1): Acquiring new postgres connection "rpc.my_new_project.request".
2021-07-11 23:46:29.448141 (Thread-1): Compiling rpc.my_new_project.request
2021-07-11 23:46:29.450460 (Thread-1): finished collecting timing info
2021-07-11 23:46:29.450570 (Thread-1): Using postgres connection "rpc.my_new_project.request".
2021-07-11 23:46:29.450620 (Thread-1): On rpc.my_new_project.request: select * 
from "d15em1n30ihttu"."dbt_ealizadeh"."population" 
join on "d15em1n30ihttu"."dbt_ealizadeh"."covid19_latest_stats" 
where code='USA'
limit 500
/* limit added automatically by dbt cloud */
2021-07-11 23:46:29.450673 (Thread-1): Opening a new connection, currently in state init
2021-07-11 23:46:29.467612 (Thread-1): Postgres error: syntax error at or near "on"
LINE 3: join on "d15em1n30ihttu"."dbt_ealizadeh"."covid19_latest_sta...
             ^

2021-07-11 23:46:29.467735 (Thread-1): finished collecting timing info
2021-07-11 23:46:29.467820 (Thread-1): On rpc.my_new_project.request: Close
2021-07-11 23:46:29.467993 (Thread-1): Got an exception: Database Error
  syntax error at or near "on"
  LINE 3: join on "d15em1n30ihttu"."dbt_ealizadeh"."covid19_latest_sta...
               ^
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/postgres/connections.py", line 47, in exception_handler
    yield
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/sql/connections.py", line 80, in add_query
    cursor.execute(sql, bindings)
psycopg2.errors.SyntaxError: syntax error at or near "on"
LINE 3: join on "d15em1n30ihttu"."dbt_ealizadeh"."covid19_latest_sta...
             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 344, in safe_run
    result = self.compile_and_execute(manifest, ctx)
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 287, in compile_and_execute
    result = self.run(ctx.node, manifest)
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 389, in run
    return self.execute(compiled_node, manifest)
  File "/usr/local/lib/python3.8/dist-packages/dbt/rpc/node_runners.py", line 90, in execute
    _, execute_result = self.adapter.execute(
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/base/impl.py", line 227, in execute
    return self.connections.execute(
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/sql/connections.py", line 124, in execute
    _, cursor = self.add_query(sql, auto_begin)
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/sql/connections.py", line 87, in add_query
    return connection, cursor
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/postgres/connections.py", line 58, in exception_handler
    raise dbt.exceptions.DatabaseException(str(e).strip()) from e
dbt.exceptions.DatabaseException: Database Error
  syntax error at or near "on"
  LINE 3: join on "d15em1n30ihttu"."dbt_ealizadeh"."covid19_latest_sta...
               ^
2021-07-11 23:46:29.469077 (Thread-1): Got exception RPCException(10003, Database Error, {'type': 'DatabaseException', 'message': 'Database Error in rpc request (from remote system)\n  syntax error at or near "on"\n  LINE 3: join on "d15em1n30ihttu"."dbt_ealizadeh"."covid19_latest_sta...\n               ^', 'raw_sql': 'select * \nfrom {{ref(\'population\')}} \njoin on {{ref(\'covid19_latest_stats\')}} \nwhere code=\'{{ var("selected_country") }}\'\nlimit 500\n/* limit added automatically by dbt cloud */', 'compiled_sql': 'select * \nfrom "d15em1n30ihttu"."dbt_ealizadeh"."population" \njoin on "d15em1n30ihttu"."dbt_ealizadeh"."covid19_latest_stats" \nwhere code=\'USA\'\nlimit 500\n/* limit added automatically by dbt cloud */', 'tags': None}, None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/rpc/sql_commands.py", line 145, in _in_thread
    self.node_results.append(runner.safe_run(self.manifest))
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 360, in safe_run
    result = self.error_result(ctx.node, error, started, [])
  File "/usr/local/lib/python3.8/dist-packages/dbt/rpc/node_runners.py", line 56, in error_result
    raise error
dbt.rpc.error.RPCException: RPCException(10003, Database Error, {'type': 'DatabaseException', 'message': 'Database Error in rpc request (from remote system)\n  syntax error at or near "on"\n  LINE 3: join on "d15em1n30ihttu"."dbt_ealizadeh"."covid19_latest_sta...\n               ^', 'raw_sql': 'select * \nfrom {{ref(\'population\')}} \njoin on {{ref(\'covid19_latest_stats\')}} \nwhere code=\'{{ var("selected_country") }}\'\nlimit 500\n/* limit added automatically by dbt cloud */', 'compiled_sql': 'select * \nfrom "d15em1n30ihttu"."dbt_ealizadeh"."population" \njoin on "d15em1n30ihttu"."dbt_ealizadeh"."covid19_latest_stats" \nwhere code=\'USA\'\nlimit 500\n/* limit added automatically by dbt cloud */', 'tags': None}, None)
2021-07-11 23:46:29.657126 (Thread-19): handling poll request
2021-07-11 23:46:29.657439 (Thread-19): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '3b89af83-316b-4b8a-9261-5739925493ab', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9fc142dac0>]}
2021-07-11 23:46:29.658362 (Thread-19): sending response (<Response 9631 bytes [200 OK]>) to 10.0.8.196
2021-07-11 23:46:45.688893 (Thread-20): handling status request
2021-07-11 23:46:45.689198 (Thread-20): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '3b89af83-316b-4b8a-9261-5739925493ab', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9fc142dd00>]}
2021-07-11 23:46:45.689764 (Thread-20): sending response (<Response 1620 bytes [200 OK]>) to 10.0.10.17
2021-07-11 23:46:45.826624 (Thread-21): handling status request
2021-07-11 23:46:45.826894 (Thread-21): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '3b89af83-316b-4b8a-9261-5739925493ab', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9fc142d790>]}
2021-07-11 23:46:45.827401 (Thread-21): sending response (<Response 1620 bytes [200 OK]>) to 10.0.15.143
2021-07-11 23:46:45.911698 (Thread-22): handling cli_args request
2021-07-11 23:46:45.911989 (Thread-22): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '3b89af83-316b-4b8a-9261-5739925493ab', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9fc142d6a0>]}
2021-07-11 23:46:47.559012 (Thread-22): sending response (<Response 138 bytes [200 OK]>) to 10.0.44.180
2021-07-11 23:46:47.596019 (MainThread): Partial parsing not enabled
2021-07-11 23:46:47.597111 (MainThread): Parsing macros/adapters.sql
2021-07-11 23:46:47.617822 (MainThread): Parsing macros/relations.sql
2021-07-11 23:46:47.619353 (MainThread): Parsing macros/catalog.sql
2021-07-11 23:46:47.621699 (MainThread): Parsing macros/materializations/snapshot_merge.sql
2021-07-11 23:46:47.624194 (MainThread): Parsing macros/core.sql
2021-07-11 23:46:47.628200 (MainThread): Parsing macros/materializations/helpers.sql
2021-07-11 23:46:47.637074 (MainThread): Parsing macros/materializations/common/merge.sql
2021-07-11 23:46:47.650971 (MainThread): Parsing macros/materializations/snapshot/snapshot_merge.sql
2021-07-11 23:46:47.652753 (MainThread): Parsing macros/materializations/snapshot/strategies.sql
2021-07-11 23:46:47.670294 (MainThread): Parsing macros/materializations/snapshot/snapshot.sql
2021-07-11 23:46:47.701515 (MainThread): Parsing macros/materializations/view/create_or_replace_view.sql
2021-07-11 23:46:47.706460 (MainThread): Parsing macros/materializations/view/view.sql
2021-07-11 23:46:47.712595 (MainThread): Parsing macros/materializations/seed/seed.sql
2021-07-11 23:46:47.759217 (Thread-23): handling poll request
2021-07-11 23:46:47.759581 (Thread-23): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '3b89af83-316b-4b8a-9261-5739925493ab', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9fc09238b0>]}
2021-07-11 23:46:47.760539 (Thread-23): sending response (<Response 4139 bytes [200 OK]>) to 10.0.4.229
2021-07-11 23:46:47.761997 (MainThread): Parsing macros/materializations/table/table.sql
2021-07-11 23:46:47.768865 (MainThread): Parsing macros/materializations/incremental/helpers.sql
2021-07-11 23:46:47.770789 (MainThread): Parsing macros/materializations/incremental/incremental.sql
2021-07-11 23:46:47.776781 (MainThread): Parsing macros/etc/is_incremental.sql
2021-07-11 23:46:47.778443 (MainThread): Parsing macros/etc/query.sql
2021-07-11 23:46:47.779569 (MainThread): Parsing macros/etc/datetime.sql
2021-07-11 23:46:47.788363 (MainThread): Parsing macros/etc/get_custom_alias.sql
2021-07-11 23:46:47.789371 (MainThread): Parsing macros/etc/get_custom_database.sql
2021-07-11 23:46:47.791163 (MainThread): Parsing macros/etc/get_custom_schema.sql
2021-07-11 23:46:47.793181 (MainThread): Parsing macros/schema_tests/not_null.sql
2021-07-11 23:46:47.794775 (MainThread): Parsing macros/schema_tests/accepted_values.sql
2021-07-11 23:46:47.797476 (MainThread): Parsing macros/schema_tests/relationships.sql
2021-07-11 23:46:47.799414 (MainThread): Parsing macros/schema_tests/unique.sql
2021-07-11 23:46:47.801194 (MainThread): Parsing macros/adapters/common.sql
2021-07-11 23:46:47.851044 (MainThread): Partial parsing not enabled
2021-07-11 23:46:48.008929 (MainThread): Acquiring new postgres connection "model.my_new_project.using_dbt_utils_macros".
2021-07-11 23:46:48.022205 (MainThread): Acquiring new postgres connection "model.my_new_project.population".
2021-07-11 23:46:48.027498 (MainThread): Acquiring new postgres connection "model.my_new_project.using_variable".
2021-07-11 23:46:48.033744 (MainThread): Acquiring new postgres connection "model.my_new_project.covid19_latest_stats".
2021-07-11 23:46:48.151945 (MainThread): [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.my_new_project.example

2021-07-11 23:46:48.152275 (MainThread): Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '370fc868-200a-46d8-8b88-ce185db5107e', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7effc0365160>]}
2021-07-11 23:46:48.163534 (MainThread): Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': '370fc868-200a-46d8-8b88-ce185db5107e', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7effc045beb0>]}
2021-07-11 23:46:48.163759 (MainThread): Found 4 models, 2 tests, 0 snapshots, 0 analyses, 138 macros, 0 operations, 0 seed files, 0 sources, 0 exposures
2021-07-11 23:46:48.164384 (MainThread): 
2021-07-11 23:46:48.164624 (MainThread): Acquiring new postgres connection "master".
2021-07-11 23:46:48.165530 (ThreadPoolExecutor-0_0): Acquiring new postgres connection "list_d15em1n30ihttu".
2021-07-11 23:46:48.174425 (ThreadPoolExecutor-0_0): Using postgres connection "list_d15em1n30ihttu".
2021-07-11 23:46:48.174501 (ThreadPoolExecutor-0_0): On list_d15em1n30ihttu: /* {"app": "dbt", "dbt_version": "0.19.2", "profile_name": "user", "target_name": "default", "connection_name": "list_d15em1n30ihttu"} */

    select distinct nspname from pg_namespace
  
2021-07-11 23:46:48.174560 (ThreadPoolExecutor-0_0): Opening a new connection, currently in state init
2021-07-11 23:46:48.193718 (ThreadPoolExecutor-0_0): SQL status: SELECT 5 in 0.02 seconds
2021-07-11 23:46:48.195887 (ThreadPoolExecutor-0_0): On list_d15em1n30ihttu: Close
2021-07-11 23:46:48.197054 (ThreadPoolExecutor-1_0): Acquiring new postgres connection "list_d15em1n30ihttu_dbt_ealizadeh".
2021-07-11 23:46:48.201827 (ThreadPoolExecutor-1_0): Using postgres connection "list_d15em1n30ihttu_dbt_ealizadeh".
2021-07-11 23:46:48.201895 (ThreadPoolExecutor-1_0): On list_d15em1n30ihttu_dbt_ealizadeh: BEGIN
2021-07-11 23:46:48.202190 (ThreadPoolExecutor-1_0): Opening a new connection, currently in state closed
2021-07-11 23:46:48.221005 (ThreadPoolExecutor-1_0): SQL status: BEGIN in 0.02 seconds
2021-07-11 23:46:48.221100 (ThreadPoolExecutor-1_0): Using postgres connection "list_d15em1n30ihttu_dbt_ealizadeh".
2021-07-11 23:46:48.221149 (ThreadPoolExecutor-1_0): On list_d15em1n30ihttu_dbt_ealizadeh: /* {"app": "dbt", "dbt_version": "0.19.2", "profile_name": "user", "target_name": "default", "connection_name": "list_d15em1n30ihttu_dbt_ealizadeh"} */
select
      'd15em1n30ihttu' as database,
      tablename as name,
      schemaname as schema,
      'table' as type
    from pg_tables
    where schemaname ilike 'dbt_ealizadeh'
    union all
    select
      'd15em1n30ihttu' as database,
      viewname as name,
      schemaname as schema,
      'view' as type
    from pg_views
    where schemaname ilike 'dbt_ealizadeh'
  
2021-07-11 23:46:48.228000 (ThreadPoolExecutor-1_0): SQL status: SELECT 4 in 0.01 seconds
2021-07-11 23:46:48.228620 (ThreadPoolExecutor-1_0): On list_d15em1n30ihttu_dbt_ealizadeh: ROLLBACK
2021-07-11 23:46:48.229886 (ThreadPoolExecutor-1_0): On list_d15em1n30ihttu_dbt_ealizadeh: Close
2021-07-11 23:46:48.233535 (MainThread): Using postgres connection "master".
2021-07-11 23:46:48.233618 (MainThread): On master: BEGIN
2021-07-11 23:46:48.233674 (MainThread): Opening a new connection, currently in state init
2021-07-11 23:46:48.250791 (MainThread): SQL status: BEGIN in 0.02 seconds
2021-07-11 23:46:48.250882 (MainThread): Using postgres connection "master".
2021-07-11 23:46:48.250930 (MainThread): On master: /* {"app": "dbt", "dbt_version": "0.19.2", "profile_name": "user", "target_name": "default", "connection_name": "master"} */
with relation as (
        select
            pg_rewrite.ev_class as class,
            pg_rewrite.oid as id
        from pg_rewrite
    ),
    class as (
        select
            oid as id,
            relname as name,
            relnamespace as schema,
            relkind as kind
        from pg_class
    ),
    dependency as (
        select
            pg_depend.objid as id,
            pg_depend.refobjid as ref
        from pg_depend
    ),
    schema as (
        select
            pg_namespace.oid as id,
            pg_namespace.nspname as name
        from pg_namespace
        where nspname != 'information_schema' and nspname not like 'pg\_%'
    ),
    referenced as (
        select
            relation.id AS id,
            referenced_class.name ,
            referenced_class.schema ,
            referenced_class.kind
        from relation
        join class as referenced_class on relation.class=referenced_class.id
        where referenced_class.kind in ('r', 'v')
    ),
    relationships as (
        select
            referenced.name as referenced_name,
            referenced.schema as referenced_schema_id,
            dependent_class.name as dependent_name,
            dependent_class.schema as dependent_schema_id,
            referenced.kind as kind
        from referenced
        join dependency on referenced.id=dependency.id
        join class as dependent_class on dependency.ref=dependent_class.id
        where
            (referenced.name != dependent_class.name or
             referenced.schema != dependent_class.schema)
    )

    select
        referenced_schema.name as referenced_schema,
        relationships.referenced_name as referenced_name,
        dependent_schema.name as dependent_schema,
        relationships.dependent_name as dependent_name
    from relationships
    join schema as dependent_schema on relationships.dependent_schema_id=dependent_schema.id
    join schema as referenced_schema on relationships.referenced_schema_id=referenced_schema.id
    group by referenced_schema, referenced_name, dependent_schema, dependent_name
    order by referenced_schema, referenced_name, dependent_schema, dependent_name;
2021-07-11 23:46:48.261969 (MainThread): SQL status: SELECT 4 in 0.01 seconds
2021-07-11 23:46:48.262487 (MainThread): On master: ROLLBACK
2021-07-11 23:46:48.263607 (MainThread): Using postgres connection "master".
2021-07-11 23:46:48.263673 (MainThread): On master: BEGIN
2021-07-11 23:46:48.265740 (MainThread): SQL status: BEGIN in 0.00 seconds
2021-07-11 23:46:48.265832 (MainThread): On master: COMMIT
2021-07-11 23:46:48.265879 (MainThread): Using postgres connection "master".
2021-07-11 23:46:48.265922 (MainThread): On master: COMMIT
2021-07-11 23:46:48.266972 (MainThread): SQL status: COMMIT in 0.00 seconds
2021-07-11 23:46:48.267049 (MainThread): On master: Close
2021-07-11 23:46:48.267334 (MainThread): 23:46:48 | Concurrency: 1 threads (target='default')
2021-07-11 23:46:48.267403 (MainThread): 23:46:48 | 
2021-07-11 23:46:48.270186 (Thread-1): Began running node model.my_new_project.population
2021-07-11 23:46:48.270405 (Thread-1): 23:46:48 | 1 of 4 START view model dbt_ealizadeh.population..................... [RUN]
2021-07-11 23:46:48.270599 (Thread-1): Acquiring new postgres connection "model.my_new_project.population".
2021-07-11 23:46:48.270674 (Thread-1): Compiling model.my_new_project.population
2021-07-11 23:46:48.271574 (Thread-1): Writing injected SQL for node "model.my_new_project.population"
2021-07-11 23:46:48.308209 (Thread-1): finished collecting timing info
2021-07-11 23:46:48.327327 (Thread-1): Using postgres connection "model.my_new_project.population".
2021-07-11 23:46:48.327416 (Thread-1): On model.my_new_project.population: /* {"app": "dbt", "dbt_version": "0.19.2", "profile_name": "user", "target_name": "default", "node_id": "model.my_new_project.population"} */
drop view if exists "d15em1n30ihttu"."dbt_ealizadeh"."population__dbt_tmp" cascade
2021-07-11 23:46:48.327474 (Thread-1): Opening a new connection, currently in state closed
2021-07-11 23:46:48.344133 (Thread-1): SQL status: DROP VIEW in 0.02 seconds
2021-07-11 23:46:48.348136 (Thread-1): Using postgres connection "model.my_new_project.population".
2021-07-11 23:46:48.348206 (Thread-1): On model.my_new_project.population: /* {"app": "dbt", "dbt_version": "0.19.2", "profile_name": "user", "target_name": "default", "node_id": "model.my_new_project.population"} */
drop view if exists "d15em1n30ihttu"."dbt_ealizadeh"."population__dbt_backup" cascade
2021-07-11 23:46:48.349562 (Thread-1): SQL status: DROP VIEW in 0.00 seconds
2021-07-11 23:46:48.355516 (Thread-1): Writing runtime SQL for node "model.my_new_project.population"
2021-07-11 23:46:48.388850 (Thread-1): Using postgres connection "model.my_new_project.population".
2021-07-11 23:46:48.388931 (Thread-1): On model.my_new_project.population: BEGIN
2021-07-11 23:46:48.390140 (Thread-1): SQL status: BEGIN in 0.00 seconds
2021-07-11 23:46:48.390225 (Thread-1): Using postgres connection "model.my_new_project.population".
2021-07-11 23:46:48.390268 (Thread-1): On model.my_new_project.population: /* {"app": "dbt", "dbt_version": "0.19.2", "profile_name": "user", "target_name": "default", "node_id": "model.my_new_project.population"} */

  create view "d15em1n30ihttu"."dbt_ealizadeh"."population__dbt_tmp" as (
    select * from population_prosperity
  );

2021-07-11 23:46:48.393946 (Thread-1): SQL status: CREATE VIEW in 0.00 seconds
2021-07-11 23:46:48.400242 (Thread-1): Using postgres connection "model.my_new_project.population".
2021-07-11 23:46:48.400314 (Thread-1): On model.my_new_project.population: /* {"app": "dbt", "dbt_version": "0.19.2", "profile_name": "user", "target_name": "default", "node_id": "model.my_new_project.population"} */
alter table "d15em1n30ihttu"."dbt_ealizadeh"."population" rename to "population__dbt_backup"
2021-07-11 23:46:48.401882 (Thread-1): SQL status: ALTER TABLE in 0.00 seconds
2021-07-11 23:46:48.405152 (Thread-1): Using postgres connection "model.my_new_project.population".
2021-07-11 23:46:48.405220 (Thread-1): On model.my_new_project.population: /* {"app": "dbt", "dbt_version": "0.19.2", "profile_name": "user", "target_name": "default", "node_id": "model.my_new_project.population"} */
alter table "d15em1n30ihttu"."dbt_ealizadeh"."population__dbt_tmp" rename to "population"
2021-07-11 23:46:48.406725 (Thread-1): SQL status: ALTER TABLE in 0.00 seconds
2021-07-11 23:46:48.413767 (Thread-1): On model.my_new_project.population: COMMIT
2021-07-11 23:46:48.413837 (Thread-1): Using postgres connection "model.my_new_project.population".
2021-07-11 23:46:48.413885 (Thread-1): On model.my_new_project.population: COMMIT
2021-07-11 23:46:48.417570 (Thread-1): SQL status: COMMIT in 0.00 seconds
2021-07-11 23:46:48.420101 (Thread-1): Using postgres connection "model.my_new_project.population".
2021-07-11 23:46:48.420168 (Thread-1): On model.my_new_project.population: /* {"app": "dbt", "dbt_version": "0.19.2", "profile_name": "user", "target_name": "default", "node_id": "model.my_new_project.population"} */
drop view if exists "d15em1n30ihttu"."dbt_ealizadeh"."population__dbt_backup" cascade
2021-07-11 23:46:48.424010 (Thread-1): SQL status: DROP VIEW in 0.00 seconds
2021-07-11 23:46:48.426353 (Thread-1): finished collecting timing info
2021-07-11 23:46:48.426451 (Thread-1): On model.my_new_project.population: Close
2021-07-11 23:46:48.426885 (Thread-1): Sending event: {'category': 'dbt', 'action': 'run_model', 'label': '370fc868-200a-46d8-8b88-ce185db5107e', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7effc03f2940>]}
2021-07-11 23:46:48.427162 (Thread-1): 23:46:48 | 1 of 4 OK created view model dbt_ealizadeh.population................ [CREATE VIEW in 0.16s]
2021-07-11 23:46:48.427235 (Thread-1): Finished running node model.my_new_project.population
2021-07-11 23:46:48.427331 (Thread-1): Began running node model.my_new_project.covid19_latest_stats
2021-07-11 23:46:48.427464 (Thread-1): 23:46:48 | 2 of 4 START view model dbt_ealizadeh.covid19_latest_stats........... [RUN]
2021-07-11 23:46:48.427640 (Thread-1): Acquiring new postgres connection "model.my_new_project.covid19_latest_stats".
2021-07-11 23:46:48.427707 (Thread-1): Compiling model.my_new_project.covid19_latest_stats
2021-07-11 23:46:48.428577 (Thread-1): Writing injected SQL for node "model.my_new_project.covid19_latest_stats"
2021-07-11 23:46:48.442297 (Thread-1): finished collecting timing info
2021-07-11 23:46:48.444423 (Thread-1): Using postgres connection "model.my_new_project.covid19_latest_stats".
2021-07-11 23:46:48.444493 (Thread-1): On model.my_new_project.covid19_latest_stats: /* {"app": "dbt", "dbt_version": "0.19.2", "profile_name": "user", "target_name": "default", "node_id": "model.my_new_project.covid19_latest_stats"} */
drop view if exists "d15em1n30ihttu"."dbt_ealizadeh"."covid19_latest_stats__dbt_tmp" cascade
2021-07-11 23:46:48.444549 (Thread-1): Opening a new connection, currently in state closed
2021-07-11 23:46:48.462227 (Thread-1): SQL status: DROP VIEW in 0.02 seconds
2021-07-11 23:46:48.465132 (Thread-1): Using postgres connection "model.my_new_project.covid19_latest_stats".
2021-07-11 23:46:48.465199 (Thread-1): On model.my_new_project.covid19_latest_stats: /* {"app": "dbt", "dbt_version": "0.19.2", "profile_name": "user", "target_name": "default", "node_id": "model.my_new_project.covid19_latest_stats"} */
drop view if exists "d15em1n30ihttu"."dbt_ealizadeh"."covid19_latest_stats__dbt_backup" cascade
2021-07-11 23:46:48.466462 (Thread-1): SQL status: DROP VIEW in 0.00 seconds
2021-07-11 23:46:48.469215 (Thread-1): Writing runtime SQL for node "model.my_new_project.covid19_latest_stats"
2021-07-11 23:46:48.481434 (Thread-1): Using postgres connection "model.my_new_project.covid19_latest_stats".
2021-07-11 23:46:48.481512 (Thread-1): On model.my_new_project.covid19_latest_stats: BEGIN
2021-07-11 23:46:48.482634 (Thread-1): SQL status: BEGIN in 0.00 seconds
2021-07-11 23:46:48.482705 (Thread-1): Using postgres connection "model.my_new_project.covid19_latest_stats".
2021-07-11 23:46:48.482749 (Thread-1): On model.my_new_project.covid19_latest_stats: /* {"app": "dbt", "dbt_version": "0.19.2", "profile_name": "user", "target_name": "default", "node_id": "model.my_new_project.covid19_latest_stats"} */

  create view "d15em1n30ihttu"."dbt_ealizadeh"."covid19_latest_stats__dbt_tmp" as (
    select * from covid_latest
  );

2021-07-11 23:46:48.496165 (Thread-1): SQL status: CREATE VIEW in 0.01 seconds
2021-07-11 23:46:48.499136 (Thread-1): Using postgres connection "model.my_new_project.covid19_latest_stats".
2021-07-11 23:46:48.499203 (Thread-1): On model.my_new_project.covid19_latest_stats: /* {"app": "dbt", "dbt_version": "0.19.2", "profile_name": "user", "target_name": "default", "node_id": "model.my_new_project.covid19_latest_stats"} */
alter table "d15em1n30ihttu"."dbt_ealizadeh"."covid19_latest_stats" rename to "covid19_latest_stats__dbt_backup"
2021-07-11 23:46:48.501073 (Thread-1): SQL status: ALTER TABLE in 0.00 seconds
2021-07-11 23:46:48.504242 (Thread-1): Using postgres connection "model.my_new_project.covid19_latest_stats".
2021-07-11 23:46:48.504310 (Thread-1): On model.my_new_project.covid19_latest_stats: /* {"app": "dbt", "dbt_version": "0.19.2", "profile_name": "user", "target_name": "default", "node_id": "model.my_new_project.covid19_latest_stats"} */
alter table "d15em1n30ihttu"."dbt_ealizadeh"."covid19_latest_stats__dbt_tmp" rename to "covid19_latest_stats"
2021-07-11 23:46:48.506304 (Thread-1): SQL status: ALTER TABLE in 0.00 seconds
2021-07-11 23:46:48.508572 (Thread-1): On model.my_new_project.covid19_latest_stats: COMMIT
2021-07-11 23:46:48.508640 (Thread-1): Using postgres connection "model.my_new_project.covid19_latest_stats".
2021-07-11 23:46:48.508686 (Thread-1): On model.my_new_project.covid19_latest_stats: COMMIT
2021-07-11 23:46:48.512033 (Thread-1): SQL status: COMMIT in 0.00 seconds
2021-07-11 23:46:48.512986 (Thread-1): Using postgres connection "model.my_new_project.covid19_latest_stats".
2021-07-11 23:46:48.513240 (Thread-1): On model.my_new_project.covid19_latest_stats: /* {"app": "dbt", "dbt_version": "0.19.2", "profile_name": "user", "target_name": "default", "node_id": "model.my_new_project.covid19_latest_stats"} */
drop view if exists "d15em1n30ihttu"."dbt_ealizadeh"."covid19_latest_stats__dbt_backup" cascade
2021-07-11 23:46:48.516516 (Thread-1): SQL status: DROP VIEW in 0.00 seconds
2021-07-11 23:46:48.518843 (Thread-1): finished collecting timing info
2021-07-11 23:46:48.518939 (Thread-1): On model.my_new_project.covid19_latest_stats: Close
2021-07-11 23:46:48.519364 (Thread-1): Sending event: {'category': 'dbt', 'action': 'run_model', 'label': '370fc868-200a-46d8-8b88-ce185db5107e', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7effc00c9ee0>]}
2021-07-11 23:46:48.519636 (Thread-1): 23:46:48 | 2 of 4 OK created view model dbt_ealizadeh.covid19_latest_stats...... [CREATE VIEW in 0.09s]
2021-07-11 23:46:48.519708 (Thread-1): Finished running node model.my_new_project.covid19_latest_stats
2021-07-11 23:46:48.519804 (Thread-1): Began running node model.my_new_project.using_dbt_utils_macros
2021-07-11 23:46:48.519935 (Thread-1): 23:46:48 | 3 of 4 START view model dbt_ealizadeh.using_dbt_utils_macros......... [RUN]
2021-07-11 23:46:48.520112 (Thread-1): Acquiring new postgres connection "model.my_new_project.using_dbt_utils_macros".
2021-07-11 23:46:48.520179 (Thread-1): Compiling model.my_new_project.using_dbt_utils_macros
2021-07-11 23:46:48.523415 (Thread-1): finished collecting timing info
2021-07-11 23:46:48.523659 (Thread-1): Compilation Error in model using_dbt_utils_macros (models/using_dbt_utils_macros.sql)
  'dbt_utils' is undefined
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dbt/clients/jinja.py", line 501, in catch_jinja
    yield
  File "/usr/local/lib/python3.8/dist-packages/dbt/clients/jinja.py", line 533, in render_template
    return template.render(ctx)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.8/dist-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 3, in top-level template code
  File "/usr/local/lib/python3.8/dist-packages/jinja2/sandbox.py", line 407, in getattr
    value = getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'dbt_utils' is undefined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 344, in safe_run
    result = self.compile_and_execute(manifest, ctx)
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 281, in compile_and_execute
    ctx.node = self.compile(manifest)
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/compile.py", line 32, in compile
    return compiler.compile_node(self.node, manifest, {})
  File "/usr/local/lib/python3.8/dist-packages/dbt/compilation.py", line 509, in compile_node
    node = self._compile_node(node, manifest, extra_context)
  File "/usr/local/lib/python3.8/dist-packages/dbt/compilation.py", line 410, in _compile_node
    compiled_node.compiled_sql = jinja.get_rendered(
  File "/usr/local/lib/python3.8/dist-packages/dbt/clients/jinja.py", line 582, in get_rendered
    return render_template(template, ctx, node)
  File "/usr/local/lib/python3.8/dist-packages/dbt/clients/jinja.py", line 533, in render_template
    return template.render(ctx)
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/dist-packages/dbt/clients/jinja.py", line 506, in catch_jinja
    raise CompilationException(str(e), node) from e
dbt.exceptions.CompilationException: Compilation Error in model using_dbt_utils_macros (models/using_dbt_utils_macros.sql)
  'dbt_utils' is undefined
2021-07-11 23:46:48.524929 (Thread-1): Sending event: {'category': 'dbt', 'action': 'run_model', 'label': '370fc868-200a-46d8-8b88-ce185db5107e', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7effc0323e80>]}
2021-07-11 23:46:48.525161 (Thread-1): 23:46:48 | 3 of 4 ERROR creating view model dbt_ealizadeh.using_dbt_utils_macros [ERROR in 0.00s]
2021-07-11 23:46:48.525226 (Thread-1): Finished running node model.my_new_project.using_dbt_utils_macros
2021-07-11 23:46:48.525326 (Thread-1): Began running node model.my_new_project.using_variable
2021-07-11 23:46:48.525456 (Thread-1): 23:46:48 | 4 of 4 START view model dbt_ealizadeh.using_variable................. [RUN]
2021-07-11 23:46:48.525632 (Thread-1): Acquiring new postgres connection "model.my_new_project.using_variable".
2021-07-11 23:46:48.525695 (Thread-1): Compiling model.my_new_project.using_variable
2021-07-11 23:46:48.528830 (Thread-1): Writing injected SQL for node "model.my_new_project.using_variable"
2021-07-11 23:46:48.541801 (Thread-1): finished collecting timing info
2021-07-11 23:46:48.543742 (Thread-1): Using postgres connection "model.my_new_project.using_variable".
2021-07-11 23:46:48.543812 (Thread-1): On model.my_new_project.using_variable: /* {"app": "dbt", "dbt_version": "0.19.2", "profile_name": "user", "target_name": "default", "node_id": "model.my_new_project.using_variable"} */
drop view if exists "d15em1n30ihttu"."dbt_ealizadeh"."using_variable__dbt_tmp" cascade
2021-07-11 23:46:48.543867 (Thread-1): Opening a new connection, currently in state closed
2021-07-11 23:46:48.559466 (Thread-1): SQL status: DROP VIEW in 0.02 seconds
2021-07-11 23:46:48.562666 (Thread-1): Using postgres connection "model.my_new_project.using_variable".
2021-07-11 23:46:48.562735 (Thread-1): On model.my_new_project.using_variable: /* {"app": "dbt", "dbt_version": "0.19.2", "profile_name": "user", "target_name": "default", "node_id": "model.my_new_project.using_variable"} */
drop view if exists "d15em1n30ihttu"."dbt_ealizadeh"."using_variable__dbt_backup" cascade
2021-07-11 23:46:48.564037 (Thread-1): SQL status: DROP VIEW in 0.00 seconds
2021-07-11 23:46:48.566443 (Thread-1): Writing runtime SQL for node "model.my_new_project.using_variable"
2021-07-11 23:46:48.579841 (Thread-1): Using postgres connection "model.my_new_project.using_variable".
2021-07-11 23:46:48.579919 (Thread-1): On model.my_new_project.using_variable: BEGIN
2021-07-11 23:46:48.581109 (Thread-1): SQL status: BEGIN in 0.00 seconds
2021-07-11 23:46:48.581182 (Thread-1): Using postgres connection "model.my_new_project.using_variable".
2021-07-11 23:46:48.581227 (Thread-1): On model.my_new_project.using_variable: /* {"app": "dbt", "dbt_version": "0.19.2", "profile_name": "user", "target_name": "default", "node_id": "model.my_new_project.using_variable"} */

  create view "d15em1n30ihttu"."dbt_ealizadeh"."using_variable__dbt_tmp" as (
    select * 
from "d15em1n30ihttu"."dbt_ealizadeh"."population" 
join on "d15em1n30ihttu"."dbt_ealizadeh"."covid19_latest_stats" 
where code='USA'
  );

2021-07-11 23:46:48.582510 (Thread-1): Postgres error: syntax error at or near "on"
LINE 6: join on "d15em1n30ihttu"."dbt_ealizadeh"."covid19_latest_sta...
             ^

2021-07-11 23:46:48.582578 (Thread-1): On model.my_new_project.using_variable: ROLLBACK
2021-07-11 23:46:48.583719 (Thread-1): finished collecting timing info
2021-07-11 23:46:48.583812 (Thread-1): On model.my_new_project.using_variable: Close
2021-07-11 23:46:48.584131 (Thread-1): Database Error in model using_variable (models/using_variable.sql)
  syntax error at or near "on"
  LINE 6: join on "d15em1n30ihttu"."dbt_ealizadeh"."covid19_latest_sta...
               ^
  compiled SQL at target/run/my_new_project/models/using_variable.sql
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/postgres/connections.py", line 47, in exception_handler
    yield
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/sql/connections.py", line 80, in add_query
    cursor.execute(sql, bindings)
psycopg2.errors.SyntaxError: syntax error at or near "on"
LINE 6: join on "d15em1n30ihttu"."dbt_ealizadeh"."covid19_latest_sta...
             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 344, in safe_run
    result = self.compile_and_execute(manifest, ctx)
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 287, in compile_and_execute
    result = self.run(ctx.node, manifest)
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 389, in run
    return self.execute(compiled_node, manifest)
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/run.py", line 248, in execute
    result = MacroGenerator(materialization_macro, context)()
  File "/usr/local/lib/python3.8/dist-packages/dbt/clients/jinja.py", line 332, in __call__
    return self.call_macro(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/dbt/clients/jinja.py", line 259, in call_macro
    return macro(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/runtime.py", line 675, in __call__
    return self._invoke(arguments, autoescape)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 61, in macro
  File "/usr/local/lib/python3.8/dist-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/runtime.py", line 290, in call
    return __obj(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/dbt/clients/jinja.py", line 332, in __call__
    return self.call_macro(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/dbt/clients/jinja.py", line 259, in call_macro
    return macro(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/runtime.py", line 675, in __call__
    return self._invoke(arguments, autoescape)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 41, in macro
  File "/usr/local/lib/python3.8/dist-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/runtime.py", line 290, in call
    return __obj(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/base/impl.py", line 227, in execute
    return self.connections.execute(
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/sql/connections.py", line 124, in execute
    _, cursor = self.add_query(sql, auto_begin)
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/sql/connections.py", line 87, in add_query
    return connection, cursor
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/postgres/connections.py", line 58, in exception_handler
    raise dbt.exceptions.DatabaseException(str(e).strip()) from e
dbt.exceptions.DatabaseException: Database Error in model using_variable (models/using_variable.sql)
  syntax error at or near "on"
  LINE 6: join on "d15em1n30ihttu"."dbt_ealizadeh"."covid19_latest_sta...
               ^
  compiled SQL at target/run/my_new_project/models/using_variable.sql
2021-07-11 23:46:48.585176 (Thread-1): Sending event: {'category': 'dbt', 'action': 'run_model', 'label': '370fc868-200a-46d8-8b88-ce185db5107e', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7effc00f08b0>]}
2021-07-11 23:46:48.585428 (Thread-1): 23:46:48 | 4 of 4 ERROR creating view model dbt_ealizadeh.using_variable........ [ERROR in 0.06s]
2021-07-11 23:46:48.585497 (Thread-1): Finished running node model.my_new_project.using_variable
2021-07-11 23:46:48.586656 (MainThread): Acquiring new postgres connection "master".
2021-07-11 23:46:48.586773 (MainThread): Using postgres connection "master".
2021-07-11 23:46:48.586823 (MainThread): On master: BEGIN
2021-07-11 23:46:48.586875 (MainThread): Opening a new connection, currently in state closed
2021-07-11 23:46:48.601601 (MainThread): SQL status: BEGIN in 0.01 seconds
2021-07-11 23:46:48.601701 (MainThread): On master: COMMIT
2021-07-11 23:46:48.601750 (MainThread): Using postgres connection "master".
2021-07-11 23:46:48.601794 (MainThread): On master: COMMIT
2021-07-11 23:46:48.602869 (MainThread): SQL status: COMMIT in 0.00 seconds
2021-07-11 23:46:48.602964 (MainThread): On master: Close
2021-07-11 23:46:48.603376 (MainThread): 23:46:48 | 
2021-07-11 23:46:48.603462 (MainThread): 23:46:48 | Finished running 4 view models in 0.44s.
2021-07-11 23:46:48.603513 (MainThread): Connection 'master' was properly closed.
2021-07-11 23:46:48.603554 (MainThread): Connection 'model.my_new_project.using_variable' was properly closed.
2021-07-11 23:46:48.648931 (MainThread): 
2021-07-11 23:46:48.649040 (MainThread): Completed with 2 errors and 0 warnings:
2021-07-11 23:46:48.649099 (MainThread): 
2021-07-11 23:46:48.649153 (MainThread): Compilation Error in model using_dbt_utils_macros (models/using_dbt_utils_macros.sql)
2021-07-11 23:46:48.649197 (MainThread):   'dbt_utils' is undefined
2021-07-11 23:46:48.649240 (MainThread): 
2021-07-11 23:46:48.649286 (MainThread): Database Error in model using_variable (models/using_variable.sql)
2021-07-11 23:46:48.649326 (MainThread):   syntax error at or near "on"
2021-07-11 23:46:48.649363 (MainThread):   LINE 6: join on "d15em1n30ihttu"."dbt_ealizadeh"."covid19_latest_sta...
2021-07-11 23:46:48.649401 (MainThread):                ^
2021-07-11 23:46:48.649438 (MainThread):   compiled SQL at target/run/my_new_project/models/using_variable.sql
2021-07-11 23:46:48.649488 (MainThread): 
Done. PASS=2 WARN=0 ERROR=2 SKIP=0 TOTAL=4
2021-07-11 23:46:48.959081 (Thread-24): handling poll request
2021-07-11 23:46:48.959380 (Thread-24): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '3b89af83-316b-4b8a-9261-5739925493ab', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9fc08b0eb0>]}
2021-07-11 23:46:48.962262 (Thread-24): sending response (<Response 89693 bytes [200 OK]>) to 10.0.13.135
2021-07-11 23:46:49.395457 (Thread-25): handling status request
2021-07-11 23:46:49.395734 (Thread-25): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '3b89af83-316b-4b8a-9261-5739925493ab', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9fc08b7190>]}
2021-07-11 23:46:49.396267 (Thread-25): sending response (<Response 1620 bytes [200 OK]>) to 10.0.11.120
2021-07-11 23:46:49.407885 (Thread-26): handling status request
2021-07-11 23:46:49.408112 (Thread-26): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '3b89af83-316b-4b8a-9261-5739925493ab', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9fc08b70d0>]}
2021-07-11 23:46:49.408579 (Thread-26): sending response (<Response 1620 bytes [200 OK]>) to 10.0.10.17
2021-07-11 23:46:49.420656 (Thread-27): handling status request
2021-07-11 23:46:49.420845 (Thread-27): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '3b89af83-316b-4b8a-9261-5739925493ab', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9fc08b7160>]}
2021-07-11 23:46:49.421236 (Thread-27): sending response (<Response 1620 bytes [200 OK]>) to 10.0.4.229
2021-07-11 23:47:53.575676 (Thread-28): handling status request
2021-07-11 23:47:53.578209 (Thread-28): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '3b89af83-316b-4b8a-9261-5739925493ab', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9fc08b73d0>]}
2021-07-11 23:47:53.578723 (Thread-28): sending response (<Response 1620 bytes [200 OK]>) to 10.0.11.120
2021-07-11 23:47:53.829693 (Thread-29): handling run_sql request
2021-07-11 23:47:53.829977 (Thread-29): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '3b89af83-316b-4b8a-9261-5739925493ab', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9fc08b7580>]}
2021-07-11 23:47:55.521077 (Thread-29): sending response (<Response 138 bytes [200 OK]>) to 10.0.42.238
2021-07-11 23:47:55.531988 (MainThread): Acquiring new postgres connection "rpc.my_new_project.request".
2021-07-11 23:47:55.546363 (MainThread): Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': 'db1046ce-7117-4028-8095-36ef6dc8e175', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd302d71e50>]}
2021-07-11 23:47:55.546597 (MainThread): Found 4 models, 2 tests, 0 snapshots, 0 analyses, 138 macros, 0 operations, 0 seed files, 0 sources, 0 exposures
2021-07-11 23:47:55.546973 (Thread-1): Acquiring new postgres connection "rpc.my_new_project.request".
2021-07-11 23:47:55.547077 (Thread-1): Compiling rpc.my_new_project.request
2021-07-11 23:47:55.549339 (Thread-1): finished collecting timing info
2021-07-11 23:47:55.549449 (Thread-1): Using postgres connection "rpc.my_new_project.request".
2021-07-11 23:47:55.549500 (Thread-1): On rpc.my_new_project.request: select * 
from "d15em1n30ihttu"."dbt_ealizadeh"."population" 
join on "d15em1n30ihttu"."dbt_ealizadeh"."covid19_latest_stats" 
where code='USA'
limit 500
/* limit added automatically by dbt cloud */
2021-07-11 23:47:55.549554 (Thread-1): Opening a new connection, currently in state init
2021-07-11 23:47:55.571041 (Thread-1): Postgres error: syntax error at or near "on"
LINE 3: join on "d15em1n30ihttu"."dbt_ealizadeh"."covid19_latest_sta...
             ^

2021-07-11 23:47:55.571167 (Thread-1): finished collecting timing info
2021-07-11 23:47:55.571252 (Thread-1): On rpc.my_new_project.request: Close
2021-07-11 23:47:55.571433 (Thread-1): Got an exception: Database Error
  syntax error at or near "on"
  LINE 3: join on "d15em1n30ihttu"."dbt_ealizadeh"."covid19_latest_sta...
               ^
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/postgres/connections.py", line 47, in exception_handler
    yield
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/sql/connections.py", line 80, in add_query
    cursor.execute(sql, bindings)
psycopg2.errors.SyntaxError: syntax error at or near "on"
LINE 3: join on "d15em1n30ihttu"."dbt_ealizadeh"."covid19_latest_sta...
             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 344, in safe_run
    result = self.compile_and_execute(manifest, ctx)
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 287, in compile_and_execute
    result = self.run(ctx.node, manifest)
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 389, in run
    return self.execute(compiled_node, manifest)
  File "/usr/local/lib/python3.8/dist-packages/dbt/rpc/node_runners.py", line 90, in execute
    _, execute_result = self.adapter.execute(
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/base/impl.py", line 227, in execute
    return self.connections.execute(
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/sql/connections.py", line 124, in execute
    _, cursor = self.add_query(sql, auto_begin)
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/sql/connections.py", line 87, in add_query
    return connection, cursor
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/postgres/connections.py", line 58, in exception_handler
    raise dbt.exceptions.DatabaseException(str(e).strip()) from e
dbt.exceptions.DatabaseException: Database Error
  syntax error at or near "on"
  LINE 3: join on "d15em1n30ihttu"."dbt_ealizadeh"."covid19_latest_sta...
               ^
2021-07-11 23:47:55.572490 (Thread-1): Got exception RPCException(10003, Database Error, {'type': 'DatabaseException', 'message': 'Database Error in rpc request (from remote system)\n  syntax error at or near "on"\n  LINE 3: join on "d15em1n30ihttu"."dbt_ealizadeh"."covid19_latest_sta...\n               ^', 'raw_sql': 'select * \nfrom {{ref(\'population\')}} \njoin on {{ref(\'covid19_latest_stats\')}} \nwhere code=\'{{ var("selected_country") }}\'\nlimit 500\n/* limit added automatically by dbt cloud */', 'compiled_sql': 'select * \nfrom "d15em1n30ihttu"."dbt_ealizadeh"."population" \njoin on "d15em1n30ihttu"."dbt_ealizadeh"."covid19_latest_stats" \nwhere code=\'USA\'\nlimit 500\n/* limit added automatically by dbt cloud */', 'tags': None}, None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/rpc/sql_commands.py", line 145, in _in_thread
    self.node_results.append(runner.safe_run(self.manifest))
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 360, in safe_run
    result = self.error_result(ctx.node, error, started, [])
  File "/usr/local/lib/python3.8/dist-packages/dbt/rpc/node_runners.py", line 56, in error_result
    raise error
dbt.rpc.error.RPCException: RPCException(10003, Database Error, {'type': 'DatabaseException', 'message': 'Database Error in rpc request (from remote system)\n  syntax error at or near "on"\n  LINE 3: join on "d15em1n30ihttu"."dbt_ealizadeh"."covid19_latest_sta...\n               ^', 'raw_sql': 'select * \nfrom {{ref(\'population\')}} \njoin on {{ref(\'covid19_latest_stats\')}} \nwhere code=\'{{ var("selected_country") }}\'\nlimit 500\n/* limit added automatically by dbt cloud */', 'compiled_sql': 'select * \nfrom "d15em1n30ihttu"."dbt_ealizadeh"."population" \njoin on "d15em1n30ihttu"."dbt_ealizadeh"."covid19_latest_stats" \nwhere code=\'USA\'\nlimit 500\n/* limit added automatically by dbt cloud */', 'tags': None}, None)
2021-07-11 23:47:55.783251 (Thread-30): handling poll request
2021-07-11 23:47:55.783560 (Thread-30): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '3b89af83-316b-4b8a-9261-5739925493ab', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9fc08b6040>]}
2021-07-11 23:47:55.784448 (Thread-30): sending response (<Response 9631 bytes [200 OK]>) to 10.0.37.247
2021-07-11 23:49:12.565970 (Thread-31): handling status request
2021-07-11 23:49:12.567802 (Thread-31): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '3b89af83-316b-4b8a-9261-5739925493ab', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9fc08b6e20>]}
2021-07-11 23:49:12.568365 (Thread-31): sending response (<Response 1620 bytes [200 OK]>) to 10.0.37.247
2021-07-11 23:49:12.816862 (Thread-32): handling run_sql request
2021-07-11 23:49:12.817154 (Thread-32): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '3b89af83-316b-4b8a-9261-5739925493ab', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9fc08be040>]}
2021-07-11 23:49:14.451998 (Thread-32): sending response (<Response 138 bytes [200 OK]>) to 10.0.13.135
2021-07-11 23:49:14.462898 (MainThread): Acquiring new postgres connection "rpc.my_new_project.request".
2021-07-11 23:49:14.477486 (MainThread): Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': '5a9f4fa4-2921-45d7-bb04-3d5bd99bacc1', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f5f68c2adf0>]}
2021-07-11 23:49:14.477719 (MainThread): Found 4 models, 2 tests, 0 snapshots, 0 analyses, 138 macros, 0 operations, 0 seed files, 0 sources, 0 exposures
2021-07-11 23:49:14.478086 (Thread-1): Acquiring new postgres connection "rpc.my_new_project.request".
2021-07-11 23:49:14.478211 (Thread-1): Compiling rpc.my_new_project.request
2021-07-11 23:49:14.480464 (Thread-1): finished collecting timing info
2021-07-11 23:49:14.480572 (Thread-1): Using postgres connection "rpc.my_new_project.request".
2021-07-11 23:49:14.480623 (Thread-1): On rpc.my_new_project.request: select * 
from "d15em1n30ihttu"."dbt_ealizadeh"."population" 
inner join "d15em1n30ihttu"."dbt_ealizadeh"."covid19_latest_stats" 
on code
where code='USA'
limit 500
/* limit added automatically by dbt cloud */
2021-07-11 23:49:14.480677 (Thread-1): Opening a new connection, currently in state init
2021-07-11 23:49:14.517542 (Thread-1): Postgres error: argument of JOIN/ON must be type boolean, not type character varying
LINE 4: on code
           ^

2021-07-11 23:49:14.517664 (Thread-1): finished collecting timing info
2021-07-11 23:49:14.517749 (Thread-1): On rpc.my_new_project.request: Close
2021-07-11 23:49:14.517913 (Thread-1): Got an exception: Database Error
  argument of JOIN/ON must be type boolean, not type character varying
  LINE 4: on code
             ^
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/postgres/connections.py", line 47, in exception_handler
    yield
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/sql/connections.py", line 80, in add_query
    cursor.execute(sql, bindings)
psycopg2.errors.DatatypeMismatch: argument of JOIN/ON must be type boolean, not type character varying
LINE 4: on code
           ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 344, in safe_run
    result = self.compile_and_execute(manifest, ctx)
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 287, in compile_and_execute
    result = self.run(ctx.node, manifest)
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 389, in run
    return self.execute(compiled_node, manifest)
  File "/usr/local/lib/python3.8/dist-packages/dbt/rpc/node_runners.py", line 90, in execute
    _, execute_result = self.adapter.execute(
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/base/impl.py", line 227, in execute
    return self.connections.execute(
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/sql/connections.py", line 124, in execute
    _, cursor = self.add_query(sql, auto_begin)
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/sql/connections.py", line 87, in add_query
    return connection, cursor
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/dist-packages/dbt/adapters/postgres/connections.py", line 58, in exception_handler
    raise dbt.exceptions.DatabaseException(str(e).strip()) from e
dbt.exceptions.DatabaseException: Database Error
  argument of JOIN/ON must be type boolean, not type character varying
  LINE 4: on code
             ^
2021-07-11 23:49:14.519006 (Thread-1): Got exception RPCException(10003, Database Error, {'type': 'DatabaseException', 'message': 'Database Error in rpc request (from remote system)\n  argument of JOIN/ON must be type boolean, not type character varying\n  LINE 4: on code\n             ^', 'raw_sql': 'select * \nfrom {{ref(\'population\')}} \ninner join {{ref(\'covid19_latest_stats\')}} \non code\nwhere code=\'{{ var("selected_country") }}\'\nlimit 500\n/* limit added automatically by dbt cloud */', 'compiled_sql': 'select * \nfrom "d15em1n30ihttu"."dbt_ealizadeh"."population" \ninner join "d15em1n30ihttu"."dbt_ealizadeh"."covid19_latest_stats" \non code\nwhere code=\'USA\'\nlimit 500\n/* limit added automatically by dbt cloud */', 'tags': None}, None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/rpc/sql_commands.py", line 145, in _in_thread
    self.node_results.append(runner.safe_run(self.manifest))
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/base.py", line 360, in safe_run
    result = self.error_result(ctx.node, error, started, [])
  File "/usr/local/lib/python3.8/dist-packages/dbt/rpc/node_runners.py", line 56, in error_result
    raise error
dbt.rpc.error.RPCException: RPCException(10003, Database Error, {'type': 'DatabaseException', 'message': 'Database Error in rpc request (from remote system)\n  argument of JOIN/ON must be type boolean, not type character varying\n  LINE 4: on code\n             ^', 'raw_sql': 'select * \nfrom {{ref(\'population\')}} \ninner join {{ref(\'covid19_latest_stats\')}} \non code\nwhere code=\'{{ var("selected_country") }}\'\nlimit 500\n/* limit added automatically by dbt cloud */', 'compiled_sql': 'select * \nfrom "d15em1n30ihttu"."dbt_ealizadeh"."population" \ninner join "d15em1n30ihttu"."dbt_ealizadeh"."covid19_latest_stats" \non code\nwhere code=\'USA\'\nlimit 500\n/* limit added automatically by dbt cloud */', 'tags': None}, None)
2021-07-11 23:49:14.727442 (Thread-33): handling poll request
2021-07-11 23:49:14.727780 (Thread-33): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '3b89af83-316b-4b8a-9261-5739925493ab', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9fc08c8220>]}
2021-07-11 23:49:14.729098 (Thread-33): sending response (<Response 9549 bytes [200 OK]>) to 10.0.10.17
2021-07-11 23:49:46.665297 (Thread-34): handling status request
2021-07-11 23:49:46.665584 (Thread-34): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '3b89af83-316b-4b8a-9261-5739925493ab', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9fc08b73a0>]}
2021-07-11 23:49:46.666138 (Thread-34): sending response (<Response 1620 bytes [200 OK]>) to 10.0.31.147
2021-07-11 23:49:46.873110 (Thread-35): handling run_sql request
2021-07-11 23:49:46.873372 (Thread-35): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '3b89af83-316b-4b8a-9261-5739925493ab', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9fc08b0fa0>]}
2021-07-11 23:49:48.508000 (Thread-35): sending response (<Response 138 bytes [200 OK]>) to 10.0.31.252
2021-07-11 23:49:48.518705 (MainThread): Acquiring new postgres connection "rpc.my_new_project.request".
2021-07-11 23:49:48.528857 (MainThread): Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': 'b342e076-d867-4c37-8c4a-aff367363990', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe281652ca0>]}
2021-07-11 23:49:48.529079 (MainThread): Found 4 models, 2 tests, 0 snapshots, 0 analyses, 138 macros, 0 operations, 0 seed files, 0 sources, 0 exposures
2021-07-11 23:49:48.529458 (Thread-1): Acquiring new postgres connection "rpc.my_new_project.request".
2021-07-11 23:49:48.529560 (Thread-1): Compiling rpc.my_new_project.request
2021-07-11 23:49:48.530549 (Thread-1): finished collecting timing info
2021-07-11 23:49:48.530660 (Thread-1): Using postgres connection "rpc.my_new_project.request".
2021-07-11 23:49:48.530710 (Thread-1): On rpc.my_new_project.request: select * from covid_latest
limit 500
/* limit added automatically by dbt cloud */
2021-07-11 23:49:48.530764 (Thread-1): Opening a new connection, currently in state init
2021-07-11 23:49:48.555058 (Thread-1): SQL status: SELECT 223 in 0.02 seconds
2021-07-11 23:49:48.597886 (Thread-1): finished collecting timing info
2021-07-11 23:49:48.598034 (Thread-1): On rpc.my_new_project.request: Close
2021-07-11 23:49:48.774312 (Thread-36): handling poll request
2021-07-11 23:49:48.774614 (Thread-36): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '3b89af83-316b-4b8a-9261-5739925493ab', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9fc28fad90>]}
2021-07-11 23:49:48.785400 (Thread-36): sending response (<Response 110198 bytes [200 OK]>) to 10.0.42.238
2021-07-11 23:50:01.021433 (Thread-37): handling status request
2021-07-11 23:50:01.021721 (Thread-37): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '3b89af83-316b-4b8a-9261-5739925493ab', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9fc28faa00>]}
2021-07-11 23:50:01.022283 (Thread-37): sending response (<Response 1620 bytes [200 OK]>) to 10.0.32.40
2021-07-11 23:50:01.207188 (Thread-38): handling run_sql request
2021-07-11 23:50:01.207480 (Thread-38): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '3b89af83-316b-4b8a-9261-5739925493ab', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9fc28be490>]}
2021-07-11 23:50:02.862772 (Thread-38): sending response (<Response 138 bytes [200 OK]>) to 10.0.24.195
2021-07-11 23:50:02.873592 (MainThread): Acquiring new postgres connection "rpc.my_new_project.request".
2021-07-11 23:50:02.883996 (MainThread): Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': 'c527b8f2-7d74-492b-98d8-0fae3aa585e7', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd74afaeb20>]}
2021-07-11 23:50:02.884224 (MainThread): Found 4 models, 2 tests, 0 snapshots, 0 analyses, 138 macros, 0 operations, 0 seed files, 0 sources, 0 exposures
2021-07-11 23:50:02.884596 (Thread-1): Acquiring new postgres connection "rpc.my_new_project.request".
2021-07-11 23:50:02.884698 (Thread-1): Compiling rpc.my_new_project.request
2021-07-11 23:50:02.885678 (Thread-1): finished collecting timing info
2021-07-11 23:50:02.885790 (Thread-1): Using postgres connection "rpc.my_new_project.request".
2021-07-11 23:50:02.885841 (Thread-1): On rpc.my_new_project.request: select * from population_prosperity
limit 500
/* limit added automatically by dbt cloud */
2021-07-11 23:50:02.885894 (Thread-1): Opening a new connection, currently in state init
2021-07-11 23:50:02.907086 (Thread-1): SQL status: SELECT 500 in 0.02 seconds
2021-07-11 23:50:02.945718 (Thread-1): finished collecting timing info
2021-07-11 23:50:02.945859 (Thread-1): On rpc.my_new_project.request: Close
2021-07-11 23:50:03.094519 (Thread-39): handling poll request
2021-07-11 23:50:03.094834 (Thread-39): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '3b89af83-316b-4b8a-9261-5739925493ab', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9fc0861910>]}
2021-07-11 23:50:03.098220 (Thread-39): sending response (<Response 40844 bytes [200 OK]>) to 10.0.44.180
2021-07-11 23:50:51.002720 (Thread-40): handling status request
2021-07-11 23:50:51.003016 (Thread-40): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '3b89af83-316b-4b8a-9261-5739925493ab', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9fc0861af0>]}
2021-07-11 23:50:51.003644 (Thread-40): sending response (<Response 1620 bytes [200 OK]>) to 10.0.42.143
2021-07-11 23:50:51.237826 (Thread-41): handling run_sql request
2021-07-11 23:50:51.238103 (Thread-41): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '3b89af83-316b-4b8a-9261-5739925493ab', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9fc0861b20>]}
2021-07-11 23:50:52.859276 (Thread-41): sending response (<Response 138 bytes [200 OK]>) to 10.0.42.143
2021-07-11 23:50:52.870133 (MainThread): Acquiring new postgres connection "rpc.my_new_project.request".
2021-07-11 23:50:52.885793 (MainThread): Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': '752af83a-1e5e-4fbf-984e-c396894fb21c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fecf6f32f40>]}
2021-07-11 23:50:52.886032 (MainThread): Found 4 models, 2 tests, 0 snapshots, 0 analyses, 138 macros, 0 operations, 0 seed files, 0 sources, 0 exposures
2021-07-11 23:50:52.886423 (Thread-1): Acquiring new postgres connection "rpc.my_new_project.request".
2021-07-11 23:50:52.886529 (Thread-1): Compiling rpc.my_new_project.request
2021-07-11 23:50:52.889269 (Thread-1): finished collecting timing info
2021-07-11 23:50:52.889379 (Thread-1): Using postgres connection "rpc.my_new_project.request".
2021-07-11 23:50:52.889430 (Thread-1): On rpc.my_new_project.request: select * 
from "d15em1n30ihttu"."dbt_ealizadeh"."population" 
inner join "d15em1n30ihttu"."dbt_ealizadeh"."covid19_latest_stats" 
on "d15em1n30ihttu"."dbt_ealizadeh"."population".code = "d15em1n30ihttu"."dbt_ealizadeh"."covid19_latest_stats".iso_code 
where code='USA'
limit 500
/* limit added automatically by dbt cloud */
2021-07-11 23:50:52.889484 (Thread-1): Opening a new connection, currently in state init
2021-07-11 23:50:52.914654 (Thread-1): SQL status: SELECT 5 in 0.03 seconds
2021-07-11 23:50:52.919157 (Thread-1): finished collecting timing info
2021-07-11 23:50:52.919272 (Thread-1): On rpc.my_new_project.request: Close
2021-07-11 23:50:53.069011 (Thread-42): handling poll request
2021-07-11 23:50:53.069353 (Thread-42): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '3b89af83-316b-4b8a-9261-5739925493ab', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9fc08691f0>]}
2021-07-11 23:50:53.071358 (Thread-42): sending response (<Response 12108 bytes [200 OK]>) to 10.0.16.173
2021-07-11 23:51:08.853142 (Thread-43): Got an acceptable cached parse result
2021-07-11 23:51:09.013173 (Thread-43): Acquiring new postgres connection "model.my_new_project.using_variable".
2021-07-11 23:51:09.187941 (Thread-44): handling status request
2021-07-11 23:51:09.188446 (Thread-44): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '3b89af83-316b-4b8a-9261-5739925493ab', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9fc070b4c0>]}
2021-07-11 23:51:09.188996 (Thread-44): sending response (<Response 185 bytes [200 OK]>) to 10.0.4.229
2021-07-11 23:51:09.235910 (Thread-43): [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.my_new_project.example

2021-07-11 23:51:09.236373 (Thread-43): Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '3b89af83-316b-4b8a-9261-5739925493ab', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9fc09c8ac0>]}
2021-07-11 23:51:09.281167 (Thread-45): handling status request
2021-07-11 23:51:09.281658 (Thread-45): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '3b89af83-316b-4b8a-9261-5739925493ab', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9fc0902e20>]}
2021-07-11 23:51:09.282136 (Thread-46): handling status request
2021-07-11 23:51:09.282734 (Thread-45): sending response (<Response 1620 bytes [200 OK]>) to 10.0.31.147
2021-07-11 23:51:09.282993 (Thread-46): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '3b89af83-316b-4b8a-9261-5739925493ab', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9fc0902880>]}
2021-07-11 23:51:09.283697 (Thread-46): sending response (<Response 1620 bytes [200 OK]>) to 10.0.10.17
2021-07-11 23:51:10.417661 (Thread-47): handling status request
2021-07-11 23:51:10.417954 (Thread-47): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '3b89af83-316b-4b8a-9261-5739925493ab', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9fc09022b0>]}
2021-07-11 23:51:10.418498 (Thread-47): sending response (<Response 1620 bytes [200 OK]>) to 10.0.11.120
2021-07-11 23:58:43.653204 (MainThread): Connection 'model.my_new_project.using_variable' was properly closed.
2021-07-11 23:58:43.701909 (Thread-48): Got an acceptable cached parse result
2021-07-11 23:58:43.953077 (Thread-48): [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.my_new_project.example

2021-07-11 23:58:43.953533 (Thread-48): Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '3b89af83-316b-4b8a-9261-5739925493ab', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9fc06f43a0>]}
2021-07-11 23:58:44.020848 (Thread-49): handling status request
2021-07-11 23:58:44.021093 (Thread-49): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '3b89af83-316b-4b8a-9261-5739925493ab', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9fc06f41c0>]}
2021-07-11 23:58:44.021577 (Thread-49): sending response (<Response 1315 bytes [200 OK]>) to 10.0.40.20
2021-07-11 23:58:44.047603 (Thread-50): handling status request
2021-07-11 23:58:44.047805 (Thread-50): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '3b89af83-316b-4b8a-9261-5739925493ab', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9fc06f4100>]}
2021-07-11 23:58:44.048216 (Thread-50): sending response (<Response 1315 bytes [200 OK]>) to 10.0.31.252
2021-07-11 23:58:44.052219 (Thread-51): handling status request
2021-07-11 23:58:44.052404 (Thread-51): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '3b89af83-316b-4b8a-9261-5739925493ab', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9fc06f4f10>]}
2021-07-11 23:58:44.052779 (Thread-51): sending response (<Response 1315 bytes [200 OK]>) to 10.0.10.17
2021-07-12 00:00:40.366526 (Thread-52): Got an acceptable cached parse result
2021-07-12 00:00:40.549114 (Thread-52): Acquiring new postgres connection "model.my_new_project.jinja_and_variable_usage ".
2021-07-12 00:00:40.650584 (Thread-52): [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.my_new_project.example

2021-07-12 00:00:40.651030 (Thread-52): Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '3b89af83-316b-4b8a-9261-5739925493ab', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9fc07c8a30>]}
2021-07-12 00:00:40.713572 (Thread-53): handling status request
2021-07-12 00:00:40.714062 (Thread-53): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '3b89af83-316b-4b8a-9261-5739925493ab', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9fc07c8f10>]}
2021-07-12 00:00:40.714652 (Thread-53): sending response (<Response 1631 bytes [200 OK]>) to 10.0.16.236
2021-07-12 00:00:40.715117 (Thread-54): handling status request
2021-07-12 00:00:40.716092 (Thread-55): handling status request
2021-07-12 00:00:40.716256 (Thread-54): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '3b89af83-316b-4b8a-9261-5739925493ab', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9fc084f910>]}
2021-07-12 00:00:40.716553 (Thread-55): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '3b89af83-316b-4b8a-9261-5739925493ab', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9fc05d8f10>]}
2021-07-12 00:00:40.717012 (Thread-54): sending response (<Response 1631 bytes [200 OK]>) to 10.0.31.252
2021-07-12 00:00:40.717510 (Thread-55): sending response (<Response 1631 bytes [200 OK]>) to 10.0.16.173
2021-07-12 00:00:55.457135 (Thread-56): handling status request
2021-07-12 00:00:55.457414 (Thread-56): Sending event: {'category': 'dbt', 'action': 'rpc_request', 'label': '3b89af83-316b-4b8a-9261-5739925493ab', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9fc084fd00>]}
2021-07-12 00:00:55.457921 (Thread-56): sending response (<Response 1631 bytes [200 OK]>) to 10.0.16.173
